# Generated by Django 4.1.5 on 2023-01-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_verified_user_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default='e332837b5c57447c98f071289978bc71', verbose_name='Unique Verification UUID'),
        ),
    ]
